language: scala

jdk:
  - oraclejdk8

script:
  ## runs both regular tests and sbt-scripted integration tests
  - sbt -Dfile.encoding=UTF8 test scripted

sudo: false

# https://docs.travis-ci.com/user/languages/java/
addons:
  apt:
    packages:
      - oracle-java8-installer

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" -delete
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

deploy:
  on:
    tags: true
    branch:
      - /v[0-9]+(.[0-9]+){2}/
  provider: script
  script: sbt -Dfile.encoding=UTF8 publish
  skip_cleanup: true
